system: "{{'reasoning': False}}" # double curly braces to interpret this as string literal

user: |-
  Here is a problem for which you need to generate/complete code:
  {question}

  Please continue to complete the function with python programming language. You are not allowed to modify the given code and do the completion only.

  The solution should be in the following format:
  <think>
  # Your thoughts/reasoning here
  </think>

  ```python
  # Your code here
  ```
